[bmscriptsbox.info]
id = "cdc0842f-d628-4395-a644-b7ace9b012b0"              
name = "不忙翻译"
desc = "极简的多语言翻译脚本软件、提供美观的窗口、搭配不忙脚本盒子可实现复制文本直接实现翻译"
version = "1.0.0"
icon = "./images/fanyi.png"

[bmscriptsbox.runtime]
language = "python"
language_version = ">=3.8"
entry = "fanyi.py"
terminal = "never"                       

[[bmscriptsbox.inputs]] 
name = "translate_text"   
type = "text"
description = "需要翻译的文本内容"

[bmscriptsbox.triggers.quick_copy]                              
enabled = true    




